name: time_scheduler
description: Time Scheduler App
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.0.3
  http: ^0.13.6
  shared_preferences: ^2.1.1
  crypto: ^3.0.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
